### ISSUE TITLE
Three consecutive dots are converted to Unicode ellipses, breaking certain URLs

### ISSUE THREAD

**Issue by yokuze** [jenningsb2/copy-as-html#2]
The showdown library converts any three consecutive '.' characters into a Unicode ellipses character. This breaks URLs that contain three dots, such as Github/Gitlab compare URLs, e.g.: https://github.com/vuejs/core/compare/v3.2.32...v3.2.33

This is a known issue in showdown < 2.0: https://github.com/showdownjs/showdown/issues/634

Showdown added an `ellipsis` setting that allows you to disable the conversion of '...' to ellipses to address this issue. Updating to showdown to >= v2.0 and setting the `ellipsis` option to `false` should fix this issue.

**Comment by jenningsb2** [comment]
Addressed in the latest release
